[basic]
;specify the path of excel file, default is kb.xlsx in the same directory as the ini file.
;you also can set different path. For example:
excel_path=C:\Users\u1079313\daily-task\daily-task-sanofi.xlsx
;max number of backup files to keep before saving, default is 100.
max_backups=100

[shortcuts]
;Hot key to save content of clipboard to excel file
;Press 1 time → column B, press 2 times quickly → column A
save_clipboard=ctrl+shift+enter
;Open excel by MS Excel / WPS
open_excel=ctrl+\
;Close excel
close_excel=ctrl+q
;Show last record and position changed
show_status=alt+/
;text in one or cross multiple cells, default is multiple cell mode.
one_or_multiple_cells_mode=ctrl+F9
